// Generated by CoffeeScript 1.7.1
(function() {
  var fs, path;

  fs = require('fs');

  path = require('path');

  exports.compress = require('compression');

  exports.errorHanlder = require('errorhandler');

  exports.bodyParser = require('body-parser');

  exports.cookieParser = require('cookie-parser');

  exports.session = require('express-session');

  exports.favicon = require('static-favicon');

  exports.logger = require('morgan');

  exports.assets = require('connect-assets');

  exports.load = function(modules) {
    var name, _results;
    _results = [];
    for (name in modules) {
      path = modules[name];
      _results.push(exports[name] = require(path));
    }
    return _results;
  };

}).call(this);
